name: Check Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with: 
          submodules: true
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
           package_file: ./.github/tl_packages
      - name: Compile presentation
        env:
          TMPDIR: ${{ runner.temp }}      
        run: |
          file=$(basename -a -s .tex *.tex)  
          latexmk --pdf $file     
          mkdir art
          cp $file".pdf" art/
      - name: Upload build artifats
        uses: actions/upload-artifact@v7
        with:
          path: art
          archive: false
